format = """\
($directory)\
$os\
$git_branch\
$fill\
$nodejs\
$rust\
$golang\
$php\
$python\
$bun\
$java\
$c\
$conda\
$zig\
$cmd_duration\
$time\
\n$character\
"""

add_newline = true
command_timeout = 700
scan_timeout = 35
palette = "gentleman"

[fill]
symbol = ' '

[palettes.gentleman]
text = "#F3F6F9"
red = "#CB7C94"
green = "#B7CC85"
yellow = "#FFE066"
blue = "#7FB4CA"
mauve = "#A3B5D6"
pink = "#FF8DD7"
teal = "#7AA89F"
peach = "#DEBA87"
subtext0 = "#5C6170"
overlay0 = "#232A40"
rosewater = "#E0C15A"
flamingo = "#FF8DD7"
maroon = "#C4746E"
lavender = "#B99BF2"
subtext1 = "#8A8FA3"
overlay2 = "#313342"
overlay1 = "#191E28"
surface2 = "#27345C"
surface1 = "#232A40"
surface0 = "#191E28"
base = "none"
mantle = "#06080f"
crust = "#06080f"

[username]
show_always = true
style_user = "white bold"
style_root = "white bold"
format = '[$user ]($style)'

[character]
success_symbol = " [](bold white)"
error_symbol = " [](bold red)"
vimcmd_symbol = " [](bold yellow)"


[custom.dockerfile]
detect_files = [
  "Dockerfile",
] # can specify filters but wildcards are not supported
format = "[ 🐋](blue bold)"
symbol = "🐋"


# Directory settings
[directory]
format = "[$path](bold $style)[$read_only]($read_only_style) "
truncation_length = 4
style = "fg:blue"
read_only_style = "fg:blue"
before_repo_root_style = "fg:blue"
truncation_symbol = "…/"
truncate_to_repo = true
read_only = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"Developer" = "💻"
[cmd_duration]
format = " took [ $duration]($style) "
style = "bold fg:duration"
min_time = 500

[git_branch]
format = "-> [$symbol$branch]($style) "
style = "bold fg:git"
symbol = " "                           # Branch with oriental touch

[git_status]
format = "[$staged$modified$renamed$deleted$untracked$stashed$conflicted$ahead_behind]($style)"
style = "fg:text_color bg:git"

# Git status details (from Sin-cy)
staged = "[+${count} ](green)"
modified = "[!${count} ](yellow)"
renamed = "[»${count} ](blue)"
deleted = "[-${count} ](red)"
untracked = "[?${count} ](sapphire)"
stashed = "[≡${count} ](lavender)"
conflicted = "[✖${count} ](red bold)"

ahead = "[⇡${count} ](teal)"
behind = "[⇣${count} ](peach)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count} ](mauve)"

[docker_context]
symbol = ""
format = '[ $symbol( $context) ]($style)'


[python]
style = 'teal'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
pyenv_version_name = true
pyenv_prefix = ''

[java]
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'
version_format = "${raw}"
symbol = " "
disabled = false

[c]
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'
symbol = " "
version_format = "${raw}"
disabled = false

[zig]
format = '[[ $symbol ($version) ](fg:#FFA066)]($style)'
version_format = "${raw}"
disabled = false

[bun]
version_format = "${raw}"
format = '[[ $symbol ($version) ](fg:#DCD7BA)]($style)'
disabled = false

[nodejs]
symbol = ""
format = '[[ $symbol ($version) ](fg:#87a987)]($style)'

[rust]
symbol = ""
format = '[[ $symbol ($version) ](fg:#FF5D62)]($style)'

[golang]
symbol = ""
format = '[[ $symbol ($version) ](fg:#7FB4CA)]($style)'
detect_files = ["go.mod"]

[php]
symbol = ""
format = '[[ $symbol ($version) ](fg:#FF9E3B)]($style)'

# kubernetes
[kubernetes]
symbol = "⛵ "
style = "bold dimmed green"
disabled = false

[time]
disabled = false
time_format = "%R"                           # Hour:Minute Format
format = '[[  $time ](fg:#8BA4B0)]($style)'
